// ===== SCORING AND PLAUSIBILITY — the half of the anti-cheat that thinks =====
//
// Two jobs, both of which have to happen on the server:
//
//  1. Compute the score. The client never sends a score; it sends what happened
//     (ships sunk, seconds elapsed, hulls lost) and the formula lives here. That
//     kills "just POST 999999" outright and means the formula can be retuned
//     without shipping a new game build.
//
//  2. Decide whether what happened could have happened. These bounds are derived
//     from the game's own spawn constants (see campaign-facts.json, generated by
//     tools/extract-campaign.js) and are deliberately GENEROUS. A bound that is
//     too tight quietly flags an honest kid who had a great run, which is a far
//     worse outcome than letting a determined cheater through — the board only
//     has to be believable, not provable.

const FACTS = require('./campaign-facts.json');

const DIFFICULTIES = ['easy', 'normal', 'hard'];
const MODES = ['campaign', 'quick', 'sandbox'];

// Every derived ceiling gets multiplied by this. The spawn math below already takes
// the most favourable roll at every step; this is the margin on top of that for
// anything the model does not know about (salvaged wrecks, convoy escorts, a theater
// Andy retunes tomorrow).
const SAFETY = 1.5;

// A war that reports less than this many seconds is not a war. The server-clock check
// in server.js is what actually makes short times expensive to fake; this is just the
// floor below which we stop pretending the number is real.
const MIN_WAR_SECONDS = 15;

// Clock skew allowance when comparing the client's reported duration against the
// server's own measurement of how long the session was open.
const CLOCK_SKEW_S = 5;
const CLOCK_SKEW_RATIO = 0.02;

function theaterOf(mapIdx) {
  if (!Number.isInteger(mapIdx)) return null;
  return FACTS.theaters[mapIdx] || null;
}

function parSeconds(mapIdx) {
  const M = theaterOf(mapIdx);
  return FACTS.parBase + (M ? M.enemies : 3) * FACTS.parPerEnemy;
}

// How many enemy hulls could the game have put in the water in this many seconds?
//
// Two spawners, both read out of updateWarPacing():
//   · dynamic events fire every `55 + rand(0..45)`s and, when the roll comes up
//     'reinforce', add 1-2 hulls  ->  best case for a cheater: 2 hulls every 55s
//   · offensives fire first at `160 + rand(0..80)`s, then every
//     `(170 + rand(0..80)) * SPAWN_SLOW`s, adding up to 6 hulls each
//
// Both are assumed to roll maximally in the cheater's favour every single time.
function maxHullsSpawned(seconds, mapIdx) {
  const M = theaterOf(mapIdx);
  const base = (M ? M.enemies : 12) + (M && M.boss ? 1 : 0);
  const s = Math.max(0, seconds);

  const events = Math.ceil(s / FACTS.eventMinInterval) * FACTS.eventMaxHulls;

  const repeatInterval = FACTS.offensiveRepeatMin * FACTS.spawnSlow;
  let offensiveWaves = 0;
  if (s >= FACTS.offensiveFirstMin) {
    offensiveWaves = 1 + Math.ceil((s - FACTS.offensiveFirstMin) / repeatInterval);
  }
  const offensives = offensiveWaves * FACTS.offensiveMaxHulls;

  return base + events + offensives;
}

// Enemy aircraft come off enemy carriers, so hull count bounds them, plus a steady
// trickle for re-arm cycles. Much rougher than the hull model on purpose — planes are
// worth 3 points each, so precision here buys almost nothing.
function maxPlanesDowned(seconds, mapIdx) {
  return maxHullsSpawned(seconds, mapIdx) * 4 + Math.ceil(Math.max(0, seconds) / 20);
}

// Islands can be taken, lost to a counter-attack, and taken again, so the ceiling is
// not simply the island count.
function maxIslandsTaken(mapIdx) {
  const M = theaterOf(mapIdx);
  return (M ? M.isles : 10) * 3 + 2;
}

// ---- score formulas -------------------------------------------------------------

// Per-war score (board B / the weekly board). Time bonus and the flawless bonus are
// win-only: losing quickly is not an achievement.
function warScore(r) {
  const parT = parSeconds(r.map_idx);
  const timeBonus = r.won && r.duration_s < parT
    ? Math.round(((parT - r.duration_s) / parT) * 100)
    : 0;
  return r.sunk * 10 +
         r.planes * 3 +
         r.islands * 15 +
         r.bosses * 50 +
         (r.won ? 100 : 0) +
         (r.won && r.ships_lost === 0 ? 50 : 0) +
         timeBonus;
}

// Mirror of the game's own careerScore() in index.html. Used only to sanity-check the
// snapshot the client sends, never to overwrite it — the client is authoritative for
// its own career total, we just refuse to believe impossible jumps in it.
function careerScoreOf(c) {
  return (c.sunk || 0) * 2 + (c.planes || 0) + (c.islands || 0) * 5 +
         (c.wins || 0) * 40 + (c.bosses || 0) * 25;
}

// Mirror of the star rule in endGame(): 1 for the win, +1 under par, +1 for not
// losing a hull. Campaign only — quick battles and sandboxes are not rated.
function starsFor(r) {
  if (!r.won || r.mode !== 'campaign') return 0;
  return 1 + (r.duration_s <= parSeconds(r.map_idx) ? 1 : 0) + (r.ships_lost === 0 ? 1 : 0);
}

function masteryScore(starsTotal, medals, completed) {
  return (starsTotal || 0) * 2 + (medals || 0) * 5 + (completed ? 50 : 0);
}

// How much career score could one sitting legitimately add? Scaled by how long it has
// been since this player last submitted, because a kid who played offline all afternoon
// (declined the prompt, or the server was down) comes back with several wars' worth of
// progress in a single jump. One extra maximal war per 10 minutes of gap is far more
// headroom than anyone needs, and still catches a career that teleports to 999999.
function maxCareerDelta(seconds, gapSeconds) {
  const perWar = maxHullsSpawned(seconds, null) * 2 +
                 maxPlanesDowned(seconds, null) +
                 maxIslandsTaken(null) * 5 + 40 + 25 * 2;
  const gapWars = 1 + Math.max(0, gapSeconds || 0) / 600;
  return Math.ceil(perWar * gapWars * SAFETY);
}

// ---- validation -----------------------------------------------------------------

function isCount(v, max) {
  return Number.isInteger(v) && v >= 0 && v <= max;
}

/**
 * Check a submitted run against everything we know.
 *
 * @param r          normalized run fields (already type-checked into integers)
 * @param elapsedS   seconds the SERVER measured between /run/start and /run/finish.
 *                   Bounds are computed from this rather than from the client's
 *                   duration, because duration excludes time spent in the armory
 *                   while the wall clock does not — using the server's number is
 *                   both safer and immune to that ambiguity.
 * @returns {{ok: boolean, reasons: string[]}}
 */
function validateRun(r, elapsedS) {
  const reasons = [];

  if (!MODES.includes(r.mode)) reasons.push('mode');
  if (!DIFFICULTIES.includes(r.difficulty)) reasons.push('difficulty');
  if (r.mode === 'campaign' && !theaterOf(r.map_idx)) reasons.push('map');

  if (!isCount(r.duration_s, 24 * 3600)) reasons.push('duration-range');
  else if (r.duration_s < MIN_WAR_SECONDS) reasons.push('duration-floor');

  // You cannot have played for longer than the session was open.
  const ceiling = elapsedS + CLOCK_SKEW_S + elapsedS * CLOCK_SKEW_RATIO;
  if (r.duration_s > ceiling) reasons.push('duration-exceeds-wallclock');

  // Bound the fighting by what the spawners could have produced in the wall-clock
  // window. maxHullsSpawned is already maximally generous; SAFETY is on top of that.
  const hullCeil = Math.ceil(maxHullsSpawned(elapsedS, r.map_idx) * SAFETY);
  const planeCeil = Math.ceil(maxPlanesDowned(elapsedS, r.map_idx) * SAFETY);
  const isleCeil = Math.ceil(maxIslandsTaken(r.map_idx) * SAFETY);

  if (!isCount(r.sunk, hullCeil)) reasons.push('sunk');
  if (!isCount(r.planes, planeCeil)) reasons.push('planes');
  if (!isCount(r.islands, isleCeil)) reasons.push('islands');
  if (!isCount(r.bosses, 4)) reasons.push('bosses');
  if (!isCount(r.ships_lost, 50)) reasons.push('ships-lost');

  // A ground theater has no enemy fleet to sink and no carriers to shoot down.
  const M = theaterOf(r.map_idx);
  if (M && M.ground && r.mode === 'campaign') {
    if (r.sunk > Math.ceil(hullCeil * 0.25)) reasons.push('sunk-on-ground-map');
  }

  // Note there is deliberately no check on the star rating. Stars are DERIVED from
  // (won, duration, hulls lost) — comparing a client's stars against our own
  // recomputation of the same inputs proves nothing about the client, while the
  // rounding difference between the game's float seconds and the integer we store
  // would flag honest runs that land exactly on par. The server just computes them.

  // A quick battle ends at exactly QUICK_KILL_GOAL kills, so a win there that claims
  // fewer is describing a game that cannot have ended.
  if (r.mode === 'quick' && r.won && r.sunk < FACTS.quickKillGoal) reasons.push('quick-goal');

  return { ok: reasons.length === 0, reasons };
}

// ---- time windows -----------------------------------------------------------------

// The weekly board resets Monday 00:00 in the family's own timezone rather than UTC, so
// "this week" lines up with the week a kid actually experiences. A fixed offset means the
// boundary drifts by an hour across DST; for a leaderboard reset that is not worth
// carrying a timezone database.
function weekStart(nowMs, tzOffsetMin) {
  const d = new Date(nowMs + tzOffsetMin * 60000);
  const dow = (d.getUTCDay() + 6) % 7;              // 0 = Monday
  const midnight = Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate());
  return Math.floor((midnight - dow * 86400000 - tzOffsetMin * 60000) / 1000);
}

module.exports = {
  FACTS, DIFFICULTIES, MODES, SAFETY, MIN_WAR_SECONDS, weekStart,
  theaterOf, parSeconds,
  maxHullsSpawned, maxPlanesDowned, maxIslandsTaken, maxCareerDelta,
  warScore, careerScoreOf, starsFor, masteryScore,
  validateRun,
};
